# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  deploy:
      docker:
        - image: circleci/php:7.3-node-browsers
      
      steps:
        - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
            fingerprints:
              - "72:14:ea:79:61:df:a6:51:07:e3:2c:88:27:eb:b4:3f"

        - run:
            name: Fix host authenticity for production server
            command: ssh-keyscan 168.63.251.210 >> ~/.ssh/known_hosts

        - run:
            name: Deploy to product-server from Github
            command: |
              ssh -tt hungthinh@168.63.251.210 <<EOF
                sudo su
                cd api.enclavei3.tk/public_html/recruitment-management 
                git pull origin master
                composer update
                exit
                exit
        #- run:
            #name: Reset apache
            #command: |
              #ssh root@149.28.134.89 "sudo /etc/init.d/apache2 restart"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
              - master
              - dev